apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQVdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKYkdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNVGM0TkRNMQpNRGt4TWpBZUZ3MHlOakEzTVRnd05EQXhOVEphRncwek5qQTNNVFV3TkRBeE5USmFNRVl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56ZzBNelV3T1RFeU1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWMrRkVPZTdLYkhCaQpHRi80UVpVMkNDNkNWQUM1MHkrUHdEN0RjYnhobWxPNWFmaksvMG80KzlXTk9uaEQvZ1YrR3dsL04xM3lvbWM2Ck5yUWhhMjFXY2FOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGTHUxTGN2MzBMNEdvUTZyL2ROcjFDcGwxUCs2TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUhFYQpkNU5hd0ZnWmJZNmM3bVJSTi8wVm5qVlR0M29jY0hkNTBqNlBvV0o4QWlCSlZpd1o0ckFmRDN6SWp1K2tCdFJ5CmtjWS9SMkF5TWZJQWh0OUgyaFllSHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
    server: https://rancher-control1/k8s/clusters/local
  name: local
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQVdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKYkdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNVGM0TkRNMQpNRGt4TWpBZUZ3MHlOakEzTVRnd05EQXhOVEphRncwek5qQTNNVFV3TkRBeE5USmFNRVl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56ZzBNelV3T1RFeU1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWMrRkVPZTdLYkhCaQpHRi80UVpVMkNDNkNWQUM1MHkrUHdEN0RjYnhobWxPNWFmaksvMG80KzlXTk9uaEQvZ1YrR3dsL04xM3lvbWM2Ck5yUWhhMjFXY2FOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGTHUxTGN2MzBMNEdvUTZyL2ROcjFDcGwxUCs2TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUhFYQpkNU5hd0ZnWmJZNmM3bVJSTi8wVm5qVlR0M29jY0hkNTBqNlBvV0o4QWlCSlZpd1o0ckFmRDN6SWp1K2tCdFJ5CmtjWS9SMkF5TWZJQWh0OUgyaFllSHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
    server: https://rancher-control1
  name: rancher
contexts:
- context:
    cluster: local
    user: rancher
  name: local
- context:
    cluster: rancher
    user: rancher
  name: rancher
current-context: local
kind: Config
preferences: {}
users:
- name: rancher
  user:
    token: kubeconfig-user-zcss5vndlh:mwmwfhp7r5w29s5zq865gk6sz499wsl6nxg4q6n9lxrjbsrv5mqjzw
