- Developer:
    - GitHub Kubernetes:
        - abbr: GH
          href: https://github.com/marlowsw/kubernetes/tree/main

    - Kubernetes Docs:
        - abbr: K8S
          href: https://kubernetes.io/docs/home/

- Personal:
    - YouTube:
        - abbr: YT
          href: https://www.youtube.com/feed/subscriptions

    - ChatGPT:
        - abbr: AI
          href: https://chatgpt.com
